[install]
# Use the same version of dependencies across all environments
exact = true

[test]
# Enable React testing
preload = "./test/setup.ts"

[build]
# Configure the build output
outdir = "dist"
entrypoints = ["./src/main.tsx"]
minify = true
sourcemap = true
loader = { ".css" = "css" } 