[install]
# Use the same version of dependencies across all environments
exact = true

[build]
# Configure the build output
outdir = "dist"
entrypoints = ["./src/main.tsx"]
minify = false
sourcemap = true
loader = { ".css" = "css" } 

[serve.static]
plugins = ["bun-plugin-tailwind"]
env = "BUN_PUBLIC_*"
