ignorePatterns:
  - "**/*.lock"

checkCommands:
  fix: bun run fix
  lint: bun run lint
  # lint: bun run lint && bun run knip
  types: bun run typecheck
  # test: bun run test

beta:
  canApprovePullRequests: true
  forceAllCheckCommands: true
