// This file is automatically generated. Do not edit it directly.
import { supabaseClient as supabase } from '@/lib/supabaseClient';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabase };