# Deploy Supabase migrations when a pull-request is merged into `main`
# Closes #34

name: Deploy Supabase

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main

permissions:
  contents: read   # required for actions/checkout

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: vgddrhyjttyrathqhefb
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # - name: Apply database migrations
      #   shell: bash
      #   run: |
      #     set -euo pipefail
      #     # Derive the DB host, e.g. https://xyzcompany.supabase.co → db.xyzcompany.supabase.co
      #     HOST="$(echo "$SUPABASE_URL" | sed -e 's@https\?://@@' -e 's@/$@@')"
      #     DB_HOST="db.${HOST}"
      #     # Use the service-role key for the password
      #     DB_URL="postgres://postgres:${SUPABASE_SERVICE_ROLE_KEY}@${DB_HOST}:5432/postgres"
      #     echo "Running supabase db push against ${DB_HOST}..."
      #     supabase db push --db-url "$DB_URL"

      - run: supabase functions deploy --project-ref $PROJECT_ID
