# Deploy Supabase migrations when a pull-request is merged into `main`
# Closes #34

name: Deploy Supabase Migrations

on:
  pull_request:
    types: [closed]

permissions:
  contents: read   # required for actions/checkout

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest

    env:
      # Supabase credentials (must be set in repo secrets)
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Apply database migrations
        shell: bash
        run: |
          set -euo pipefail

          # Derive the DB host: https://xyzcompany.supabase.co → db.xyzcompany.supabase.co
          HOST="$(echo "$SUPABASE_URL" | sed -e 's@https\?://@@' -e 's@/$@@')"
          DB_HOST="db.${HOST}"

          # Connection string (service-role key used as password)
          DB_URL="postgres://postgres:${SUPABASE_SERVICE_ROLE_KEY}@${DB_HOST}:5432/postgres"

          echo "Running supabase db push against ${DB_HOST}..."
          supabase db push --db-url "$DB_URL"

      - name: Deploy Supabase edge functions
        shell: bash
        run: |
          set -euo pipefail
          echo "Deploying Supabase edge functions..."
          supabase functions deploy --all
